# visualizer.py
# ═══════════════════════════════════════════════════════════
# Visualizer — generates comparison charts from benchmark results
# ═══════════════════════════════════════════════════════════
#
# EXECUTION ORDER: Run after benchmark.py
#
# Terminal:
#   python visualizer.py
#
# Generates 3 charts in results/ folder:
#   1. abort_rate_comparison.png  — 2PL vs TO abort rates
#   2. throughput_comparison.png  — 2PL vs TO throughput
#   3. latency_heatmap.png       — Protocol × Conflict → Latency
# ═══════════════════════════════════════════════════════════

import os
import sys
import pandas as pd
import numpy as np

# Ép console trên Windows dùng UTF-8 để in tiếng Việt không bị lỗi
sys.stdout.reconfigure(encoding='utf-8')

# Use Agg backend for non-interactive rendering (no GUI needed)
# Must be set BEFORE importing pyplot
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sns
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
RESULTS_DIR = os.path.join(BASE_DIR, 'results')
RESULTS_CSV = os.path.join(RESULTS_DIR, 'results.csv')

# ─── Academic-style chart configuration ───────────────────
# Clean, professional look suitable for reports and papers
plt.rcParams.update({
    'font.family': 'serif',
    'font.size': 12,
    'axes.labelsize': 14,
    'axes.titlesize': 16,
    'legend.fontsize': 11,
    'xtick.labelsize': 11,
    'ytick.labelsize': 11,
    'figure.figsize': (10, 6),
    'figure.dpi': 150,
    'savefig.dpi': 150,
    'savefig.bbox': 'tight',
    'grid.alpha': 0.3,
})


def load_results():
    """Load benchmark results from the CSV file generated by benchmark.py.

    Returns:
        pd.DataFrame: Results with columns: protocol, conflict_density,
            abort_rate, throughput, avg_latency_ms, avg_restarts, timestamp.

    Raises:
        SystemExit: If results file doesn't exist.
    """
    if not os.path.exists(RESULTS_CSV):
        logger.error(f"Results file not found: {RESULTS_CSV}")
        logger.error("Run benchmark.py first!")
        sys.exit(1)

    df = pd.read_csv(RESULTS_CSV)
    logger.info(f"Loaded {len(df)} result rows from {RESULTS_CSV}")

    if df.empty:
        logger.error("No data found in results.csv. Cannot generate charts. Please ensure the benchmark ran successfully.")
        return

    logger.info("Generating charts...")
    return df


def find_crossover_point(df):
    """Find the crossover point where TO's abort rate exceeds 2PL's.

    Uses linear interpolation between measured data points to estimate
    the exact conflict density where the two abort rate curves cross.

    The crossover point is the key finding of this experiment:
    - Below crossover: TO is preferable (lower overhead, no locks)
    - Above crossover: 2PL is preferable (deterministic waiting beats
      excessive aborts)

    Args:
        df: Results DataFrame with protocol, conflict_density, abort_rate.

    Returns:
        tuple: (conflict_density, abort_rate) at the crossover point,
               or None if no crossover is found.
    """
    tpl_data = df[df['protocol'] == '2PL'].sort_values('conflict_density')
    to_data = df[df['protocol'] == 'TO'].sort_values('conflict_density')

    if len(tpl_data) == 0 or len(to_data) == 0:
        return None

    # Merge on conflict_density so we can compare directly
    merged = pd.merge(
        tpl_data[['conflict_density', 'abort_rate']],
        to_data[['conflict_density', 'abort_rate']],
        on='conflict_density',
        suffixes=('_2PL', '_TO')
    )

    # Compute difference: positive means TO has higher abort rate
    merged['diff'] = merged['abort_rate_TO'] - merged['abort_rate_2PL']

    # Find where the sign changes (TO crosses above 2PL)
    for i in range(len(merged) - 1):
        if merged.iloc[i]['diff'] <= 0 and merged.iloc[i + 1]['diff'] > 0:
            # Linear interpolation to find exact crossover
            x1 = merged.iloc[i]['conflict_density']
            x2 = merged.iloc[i + 1]['conflict_density']
            y1 = merged.iloc[i]['diff']
            y2 = merged.iloc[i + 1]['diff']

            # x-intercept: where diff = 0
            crossover_x = x1 + (0 - y1) * (x2 - x1) / (y2 - y1)

            # Interpolate the abort rate at the crossover
            ar1 = merged.iloc[i]['abort_rate_2PL']
            ar2 = merged.iloc[i + 1]['abort_rate_2PL']
            crossover_y = ar1 + (crossover_x - x1) * (ar2 - ar1) / (x2 - x1)

            return (crossover_x, crossover_y)

    # If TO is always higher (no crossover), report the first point where TO > 2PL
    if merged['diff'].iloc[-1] > 0:
        logger.info("Tỷ lệ abort của TO luôn cao hơn 2PL (không có điểm giao cắt)")
        first_higher = merged[merged['diff'] > 0].iloc[0]
        return (first_higher['conflict_density'], first_higher['abort_rate_2PL'])

    return None


def plot_abort_rate_comparison(df):
    """Chart 1: Abort Rate comparison — 2PL (blue) vs TO (red).

    X-axis: Conflict Density (10% to 90%)
    Y-axis: Abort Rate (%)
    Annotates the crossover point with a star ★

    This is the primary chart showing the key research finding.

    Args:
        df: Results DataFrame.
    """
    fig, ax = plt.subplots(figsize=(10, 6))

    tpl_data = df[df['protocol'] == '2PL'].sort_values('conflict_density')
    to_data = df[df['protocol'] == 'TO'].sort_values('conflict_density')

    # Plot lines with distinct markers
    ax.plot(
        tpl_data['conflict_density'] * 100,
        tpl_data['abort_rate'] * 100,
        'b-o', linewidth=2.5, markersize=8,
        label='2-Phase Locking (2PL)',
        color='#2196F3', markerfacecolor='white', markeredgewidth=2
    )

    ax.plot(
        to_data['conflict_density'] * 100,
        to_data['abort_rate'] * 100,
        'r-s', linewidth=2.5, markersize=8,
        label='Timestamp Ordering (TO)',
        color='#F44336', markerfacecolor='white', markeredgewidth=2
    )

    # Find and annotate the crossover point
    crossover = find_crossover_point(df)
    if crossover:
        cx, cy = crossover
        # Star marker at crossover
        ax.plot(
            cx * 100, cy * 100, '*',
            markersize=20, color='#FF9800',
            markeredgecolor='black', markeredgewidth=1, zorder=5
        )
        # Annotation with arrow
        ax.annotate(
            f'★ Điểm giao cắt (Crossover)\n({cx * 100:.1f}%, {cy * 100:.1f}%)',
            xy=(cx * 100, cy * 100),
            xytext=(cx * 100 + 10, cy * 100 + 5),
            fontsize=10, fontweight='bold',
            arrowprops=dict(arrowstyle='->', color='#FF9800', lw=2),
            bbox=dict(
                boxstyle='round,pad=0.3',
                facecolor='#FFF3E0', edgecolor='#FF9800'
            )
        )

    ax.set_xlabel('Mật độ Xung đột / Conflict Density (%)')
    ax.set_ylabel('Tỷ lệ Hủy / Abort Rate (%)')
    ax.set_title('So sánh Tỷ lệ Hủy (Abort Rate): 2PL vs Timestamp Ordering')
    ax.legend(loc='upper left', framealpha=0.9)
    ax.grid(True, alpha=0.3)
    ax.set_xlim([5, 95])
    ax.set_xticks([10, 30, 50, 70, 90])

    output_path = os.path.join(RESULTS_DIR, 'abort_rate_comparison.png')
    fig.savefig(output_path)
    plt.close(fig)
    logger.info(f"Chart saved: {output_path}")


def plot_throughput_comparison(df):
    """Chart 2: Throughput comparison — 2PL vs TO.

    X-axis: Conflict Density (%)
    Y-axis: Transactions per second
    Includes shaded region showing performance gap.

    Args:
        df: Results DataFrame.
    """
    fig, ax = plt.subplots(figsize=(10, 6))

    tpl_data = df[df['protocol'] == '2PL'].sort_values('conflict_density')
    to_data = df[df['protocol'] == 'TO'].sort_values('conflict_density')

    ax.plot(
        tpl_data['conflict_density'] * 100, tpl_data['throughput'],
        'b-o', linewidth=2.5, markersize=8,
        label='2-Phase Locking (2PL)',
        color='#2196F3', markerfacecolor='white', markeredgewidth=2
    )

    ax.plot(
        to_data['conflict_density'] * 100, to_data['throughput'],
        'r-s', linewidth=2.5, markersize=8,
        label='Timestamp Ordering (TO)',
        color='#F44336', markerfacecolor='white', markeredgewidth=2
    )

    # Shaded region between curves to visually show the performance gap
    # This makes it easy to see which protocol is better at each point
    ax.fill_between(
        tpl_data['conflict_density'] * 100,
        tpl_data['throughput'].values,
        to_data['throughput'].values,
        alpha=0.1, color='gray'
    )

    ax.set_xlabel('Mật độ Xung đột / Conflict Density (%)')
    ax.set_ylabel('Thông lượng / Throughput (txn/sec)')
    ax.set_title('So sánh Thông lượng (Throughput): 2PL vs Timestamp Ordering')
    ax.legend(loc='upper right', framealpha=0.9)
    ax.grid(True, alpha=0.3)
    ax.set_xlim([5, 95])
    ax.set_xticks([10, 30, 50, 70, 90])

    output_path = os.path.join(RESULTS_DIR, 'throughput_comparison.png')
    fig.savefig(output_path)
    plt.close(fig)
    logger.info(f"Chart saved: {output_path}")


def plot_latency_heatmap(df):
    """Chart 3: Latency heatmap — Protocol × Conflict Density → Avg Latency.

    Rows: Protocol (2PL, TO)
    Columns: Conflict Density levels
    Color: Average latency in milliseconds (yellow-orange-red scale)

    Heatmaps are effective for spotting patterns across two dimensions
    at a glance.

    Args:
        df: Results DataFrame.
    """
    fig, ax = plt.subplots(figsize=(10, 4))

    # Pivot data into matrix form for the heatmap
    pivot = df.pivot_table(
        index='protocol',
        columns='conflict_density',
        values='avg_latency_ms'
    )

    # Format column labels as percentages for readability
    pivot.columns = [f"{int(c * 100)}%" for c in pivot.columns]

    sns.heatmap(
        pivot, annot=True, fmt='.1f', cmap='YlOrRd',
        linewidths=0.5, ax=ax,
        cbar_kws={'label': 'Độ trễ trung bình / Avg Latency (ms)'}
    )

    ax.set_title('Bản đồ Độ trễ Trung bình / Latency Heatmap (ms)')
    ax.set_xlabel('Mật độ Xung đột / Conflict Density')
    ax.set_ylabel('Thuật toán / Protocol')

    output_path = os.path.join(RESULTS_DIR, 'latency_heatmap.png')
    fig.savefig(output_path)
    plt.close(fig)
    logger.info(f"Chart saved: {output_path}")


def generate_summary_table(df):
    """Print a formatted summary table of all benchmark results.

    Also reports the crossover point finding, which is the key
    research outcome of this experiment.

    Args:
        df: Results DataFrame.
    """
    print("\n" + "=" * 80)
    print("TÓM TẮT KẾT QUẢ BENCHMARK")
    print("=" * 80)
    print(
        f"{'Thuật toán':<10} {'Xung đột%':<12} {'Tỷ lệ Abort':<12} "
        f"{'Thông lượng':<14} {'Độ trễ(ms)':<14} {'Restarts':<10}"
    )
    print("-" * 80)

    for _, row in df.iterrows():
        print(
            f"{row['protocol']:<10} "
            f"{row['conflict_density'] * 100:<12.0f} "
            f"{row['abort_rate'] * 100:<12.2f} "
            f"{row['throughput']:<14.2f} "
            f"{row['avg_latency_ms']:<14.2f} "
            f"{row['avg_restarts']:<10.4f}"
        )

    print("=" * 80)

    # Report crossover point — the key finding
    crossover = find_crossover_point(df)
    if crossover:
        print(f"\n★ ĐIỂM GIAO CẮT: Mật độ Xung đột = {crossover[0] * 100:.1f}%")
        print(f"  Tại điểm này, tỷ lệ Abort của TO vượt quá chi phí chờ đợi của 2PL.")
        print(f"  Dưới mức này: TO tốt hơn (chi phí thấp, không phải quản lý Khóa)")
        print(f"  Trên mức này: 2PL tốt hơn (chờ đợi có trật tự tốt hơn là liên tục Abort)")
    else:
        print("\nKhông tìm thấy điểm giao cắt rõ ràng trong dữ liệu.")


def main():
    """Main entry point: load results and generate all charts."""
    logger.info("Loading benchmark results...")
    df = load_results()

    if df is None:
        logger.info("No data to visualize. Exiting.")
        return

    logger.info("Generating charts...")
    plot_abort_rate_comparison(df)
    plot_throughput_comparison(df)
    plot_latency_heatmap(df)

    generate_summary_table(df)

    logger.info(f"\nAll charts saved to {RESULTS_DIR}")
    logger.info("Done!")


if __name__ == '__main__':
    main()
